---
sidebar: sidebar 
permalink: trident-rn.html 
keywords: 'what"s new, new features, enhancements, known issues, resolved issues, troubleshooting' 
summary: 'NetApp améliore et améliore continuellement ses produits et services. Voici quelques-unes des dernières fonctionnalités, améliorations et correctifs de la dernière version d"Astra Trident.' 
---
= Notes de version
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Dans les notes de version, vous trouverez des informations sur les nouvelles fonctionnalités, les améliorations et les correctifs de bogues de la dernière version d'Astra Trident.


WARNING: Le `tridentctl` Binaire pour Linux fourni dans le fichier zip du programme d'installation est la version testée et prise en charge. Sachez que le `macos` binaire fourni dans le `/extras` une partie du fichier zip n'est pas testée ou prise en charge.



== Quoi de neuf

NetApp améliore et améliore continuellement ses produits et services. Voici quelques-unes des dernières fonctionnalités disponibles avec Astra Trident.



=== Astra Trident 21.07.02

* Problème résolu où les clones de volumes XFS n'ont pas pu être montés sur le même nœud que le volume source.




==== Améliorations

* Prise en charge ajoutée de Kubernetes 1.22.
* Compatibilité de l'opérateur Trident et du graphique Helm avec Kubernetes 1.22


Voir https://github.com/NetApp/trident/releases["Astra Trident GitHub"^] pour en savoir plus.



=== Astra Trident 21.07.01

* Résolution du problème d'installation YAML personnalisé avec une image différente.
* Problème de calcul de la taille de snapshot résolu.


Voir https://github.com/NetApp/trident/releases/tag/v21.07.1["Astra Trident GitHub"^] pour en savoir plus.



=== Astra Trident 21.07

Astra Trident 21.07.0 est *non disponible au téléchargement*. Modifications introduites dans `snapshotReserve` Avec la version 21.07.0, CSI peut se produire `VolumeSnapshots` Inutilisable pour la création de la ou des demandes de volume persistant.

Si vous avez déjà mis à niveau vers la version 21.07.0, il est recommandé de supprimer la nouvelle version créée `VolumeSnapshots` (provisionné avec la version 21.07.0) et revenir à la version précédente.

Voir https://github.com/NetApp/trident/releases/tag/v21.07.0["Astra Trident GitHub"^] pour en savoir plus.



== Problèmes connus

Les problèmes connus identifient les problèmes susceptibles de vous empêcher d'utiliser le produit avec succès.

* L'ASTRA Trident applique maintenant une blanc `fsType` (`fsType=""`) pour les volumes qui n'ont pas le `fsType` Spécifiés dans leur classe de stockage. Lorsque vous utilisez Kubernetes 1.17 ou version ultérieure, Trident prend en charge l'option vide `fsType` Pour les volumes NFS. Pour les volumes iSCSI, vous devez définir le `fsType` Sur votre classe de stockage lors de l'application d'un `fsGroup` Utilisation d'un contexte de sécurité.
* Lors de l'utilisation d'un système back-end pour plusieurs instances Trident d'Astra, chaque fichier de configuration back-end doit avoir un fichier différent `storagePrefix` Valeur pour les systèmes ONTAP back-end ou différente `TenantName` Pour les systèmes SolidFire back-end. Astra Trident ne peut pas détecter les volumes que d'autres instances d'Astra Trident ont créés. Tentative de création d'un volume existant sur un système back-end ONTAP ou SolidFire réussie, Astra Trident traite la création de volume comme une opération identente. Si `storagePrefix` ou `TenantName` n'en diffère pas, il peut y avoir des collisions de noms pour les volumes créés sur le même back-end.
* Lors de l'installation d'Astra Trident (à l'aide de `tridentctl` Ou l'opérateur Trident) et à l'aide de `tridentctl` Pour gérer Astra Trident, vous devez vous assurer que `KUBECONFIG` la variable d'environnement est définie. Cela est nécessaire pour indiquer le cluster Kubernetes `tridentctl` doit travailler contre. Lorsque vous utilisez plusieurs environnements Kubernetes, assurez-vous que `KUBECONFIG` le fichier est fourni avec précision.
* Pour réclamer de l'espace en ligne pour des volumes persistants iSCSI, le système d'exploitation sous-jacent du nœud worker peut nécessiter le passage des options de montage vers le volume. Ceci est vrai pour les instances RHEL/RedHat CoreOS qui requièrent le `discard` https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems["option de montage"^]; Assurez-vous que le mountOption de mise au rebut est inclus dans votre[`StorageClass`^] pour prendre en charge le blocage en ligne.
* Si vous possédez plusieurs instances d'Astra Trident par cluster Kubernetes, Astra Trident ne peut pas communiquer avec d'autres instances et ne peut pas détecter les autres volumes qu'ils ont créés, ce qui entraîne un comportement inattendu et incorrect si plusieurs instances s'exécutent dans un cluster. Il ne devrait y avoir qu'une seule instance d'Astra Trident par cluster Kubernetes.
* Avec Astra Trident `StorageClass` Les objets sont supprimés de Kubernetes alors que Astra Trident est hors ligne, Astra Trident ne supprime pas les classes de stockage correspondantes de la base de données lorsqu'elle est remise en ligne. Vous devez supprimer ces classes de stockage à l'aide de `tridentctl` Ou l'API REST.
* Si un utilisateur supprime un volume persistant provisionné par Astra Trident avant de supprimer le volume persistant correspondant, Astra Trident ne supprime pas automatiquement le volume de sauvegarde. Vous devez supprimer le volume via `tridentctl` Ou l'API REST.
* ONTAP ne peut pas provisionner simultanément plusieurs FlexGroup, sauf si l'ensemble d'agrégats est unique pour chaque demande de provisionnement.
* Lorsque vous utilisez Astra Trident sur IPv6, vous devez préciser `managementLIF` et `dataLIF` dans la définition du back-end entre crochets. Par exemple : ``[fd20:8b1e:b258:2000:f816:3eff:feec:0]``.
* Si vous utilisez le `solidfire-san` Pilote avec OpenShift 4.5, assurez-vous que les nœuds de travail sous-jacents utilisent MD5 comme algorithme d'authentification CHAP.




== Trouvez plus d'informations

* https://github.com/NetApp/trident["Astra Trident GitHub"^]
* https://netapp.io/persistent-storage-provisioner-for-kubernetes/["Blogs Trident d'Astra"^]

